---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tingcolc/public_html
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R assets/* $DEPLOYPATH      
    - /bin/cp -R Error/* $DEPLOYPATH  
    - /bin/cp -R forms/* $DEPLOYPATH               #copy all recursively to $DEPLOYPATH
