---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tingcolc/public_html
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH                  #copy all recursively to $DEPLOYPATH
